### ISSUE TITLE
Import WireGuard Via Patcher, Not Directly in Tree

### ISSUE THREAD

**Issue by zx2c4** [techdro-id/stormguard_mido_msm8953#2]
Some recent WireGuard changes I thought I should tell you about here.

You've been building WireGuard as part of this kernel by actually committing the WireGuard source code. *Please stop doing this*, and instead move over to the new method, which was created in response to a few recent requests and concerns. It's also an *important* thing to do, because it ensures that things actually stay up to date. [The below instructions follow from "Standalone Kernel Built-in Module" in the documentation.](https://git.zx2c4.com/android_kernel_wireguard/about/)

First remove what you did before:

```
$ rm -rf path/to/kernel/net/wireguard # or just revert your previous commit
```

Now run the persistent patcher script and commit its results:

```
$ cd /tmp && git clone https://git.zx2c4.com/android_kernel_wireguard/
$ cd android_kernel_wireguard/standalone-kernel
$ ./patch-kernel.sh path/to/kernel
$ cd /tmp && rm -rf android_kernel_wireguard
$ cd path/to/kernel && git add . && git commit -m "net/wireguard: add to tree via updater mechanism"
```

That should be all that's required. Let me know if you have any issues doing this. It's critical that you move over to using this method.

**Comment by adekmaulana** [comment]
Thank you so much for letting me know!, I will update it when i got time, and i will keep this open until inform you that patched is applied

**Comment by adekmaulana** [comment]
thanks! patched is already applied...
